version: "3"

services:
  mysql-template:
    image: mysql:latest
    profiles:
      - template
    networks:
      - acme_network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  mysql:
    extends: mysql-template
    container_name: acme-mysql
    profiles:
      - services
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: ${DATABASE_USER}
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}

  mysql-supertokens:
    extends: mysql-template
    container_name: acme-mysql-supertokens
    profiles:
      - services
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: supertokens
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: supertokens

  supertokens:
    container_name: acme-supertokens
    image: registry.supertokens.io/supertokens/supertokens-mysql:7.0
    profiles:
      - services
    depends_on:
      mysql-supertokens:
        condition: service_healthy
    ports:
      - 3567:3567
    environment:
      MYSQL_CONNECTION_URI: mysql://supertokens:password@mysql-supertokens:3306/supertokens
    networks:
      - acme_network
    restart: unless-stopped
    healthcheck:
      test: >
        bash -c 'exec 3<>/dev/tcp/127.0.0.1/3567 && echo -e "GET /hello HTTP/1.1\r\nhost: 127.0.0.1:3567\r\nConnection: close\r\n\r\n" >&3 && cat <&3 | grep "Hello"'
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  acme_network:
    name: acme_network
    driver: bridge
